### ISSUE TITLE
An COM example

### ISSUE THREAD

**Issue by mominul** [kennykerr/samples-rs#1]
An COM example would be really helpful!
This is quite a simple example introducing the concepts of using COM: https://docs.microsoft.com/en-us/windows/win32/learnwin32/example--the-open-dialog-box
I am a beginner in Windows development, so I am quite confused about how to start using the COM related APIs with the `windows` crate.

Thanks!

**Comment by kennykerr** [comment]
I have added a comprehensive COM sample here:

https://github.com/kennykerr/samples-rs/tree/master/clock

For an introduction into Windows development and COM in particular, you can check out my courses here: 

https://kennykerr.ca/courses/
