### ISSUE TITLE
Request to add an example about the mouse

### ISSUE THREAD

**Issue by chaoxi24** [kennykerr/samples-rs#4]
Request to add an example about the mouse, such as a mouse hotkey that only works on "notepad.exe".

Its structure is similar:
1. Monitor the mouse
2. Determine the window when the right button is pressed, if it comes from "notepad.exe", start recording the mouse coordinates.
3. When the right button pops up, if it is recording, print the record and end the monitoring. If there is no record, execute "CallNextHookEx()"

I'm sorry to make a request so rashly. I am a novice with no programming foundation. I want to write a "mouse gesture" software. I searched many examples of mouse gestures in C language, but when I tried to complete the same process with rust, I faced endless errors. I don't know C, and I am just getting started with Rust. I desperately need a simple example that works. Thank you.

**Comment by kennykerr** [comment]
Mouse events are reported as window messages. There are various examples illustrating message handling. I'm about to archive this repo as the examples have been moved to the main [windows-rs](https://github.com/microsoft/windows-rs) repo. Feel free to open an issue there if you still have questions.
